### ISSUE TITLE
could be sexier

### ISSUE THREAD

**Issue by anoadragon453** [abhishyantkhare/abhishyantkhare.github.io#1]

**Comment by abhishyantkhare** [comment]
then gimme some of that sweet sweet code to put in this repository and make a sensual pull request

**Comment by anoadragon453** [comment]
Bitch gimme something to work with other than a README.

Actually you know what, I'm doin' it anyways.

**Comment by abhishyantkhare** [comment]
this is less sensual than i desired

**Comment by anoadragon453** [comment]
Yes I believe the current state of the project now corresponds with what upper management had in mind. In future they may request for more sex, but that is a topic for another issue.

**Comment by abhishyantkhare** [comment]
I'm glad I always make sure that my github seems as profesional as possible when I tell employers to check out my github

**Comment by anoadragon453** [comment]
faggot

**Comment by abhishyantkhare** [comment]
👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌th 👌 ere👌👌👌 right✔there ✔✔if i do ƽaү so my selｆ 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit
